package com.pss.senha.validacao;

import java.util.TreeSet;

final class MaisUsadasTratador extends TratadorSenha {

    @Override
    public String verificar(String senha) {

        TreeSet<String> maisUsadas = new TreeSet<>();
        maisUsadas.add("1234567");
        maisUsadas.add("123456");
        maisUsadas.add("123456789");
        maisUsadas.add("102030");
        maisUsadas.add("1234");
        maisUsadas.add("010203");
        maisUsadas.add("12345");
        maisUsadas.add("654321");
        maisUsadas.add("12345678");
        maisUsadas.add("101010");
        maisUsadas.add("gabriel");
        maisUsadas.add("123mudar");
        maisUsadas.add("sucesso");
        maisUsadas.add("123123");
        maisUsadas.add("131313");
        maisUsadas.add("123");
        maisUsadas.add("abc123");
        maisUsadas.add("121212");
        maisUsadas.add("vitoria");
        maisUsadas.add("flamengo");
        maisUsadas.add("felipe");
        maisUsadas.add("brasil");
        maisUsadas.add("felicidade");
        maisUsadas.add("teste123");
        maisUsadas.add("mariana");
        maisUsadas.add("000000");
        maisUsadas.add("password");
        maisUsadas.add("qwerty");
        maisUsadas.add("asdfgh");
        maisUsadas.add("zxcvbnm");
        maisUsadas.add("qazwsx");
        maisUsadas.add("blink182");
        maisUsadas.add("lol123");
        maisUsadas.add("7777777");
        maisUsadas.add("666666");
        maisUsadas.add("jesus");
        maisUsadas.add("brasil/brazil");
        maisUsadas.add("letmein");
        maisUsadas.add("iloveyou");
        maisUsadas.add("hello123");
        maisUsadas.add("matrix");
        maisUsadas.add("admin");
        maisUsadas.add("hotmail");
        maisUsadas.add("babygirl");
        maisUsadas.add("111111");
        maisUsadas.add("sunshine");
        maisUsadas.add("princess");
        maisUsadas.add("welcome");
        maisUsadas.add("football");
        maisUsadas.add("monkey");
        maisUsadas.add("!@#$%^&*");
        maisUsadas.add("charlie");
        maisUsadas.add("aa123456");
        maisUsadas.add("donald");
        maisUsadas.add("password1");
        maisUsadas.add("qwerty123");
        maisUsadas.add("dragon");
        maisUsadas.add("ashley");
        maisUsadas.add("michael");
        maisUsadas.add("50cent");
        maisUsadas.add("eminem");
        maisUsadas.add("metallica");
        maisUsadas.add("slipknot");
        maisUsadas.add("superman");
        maisUsadas.add("naruto");
        maisUsadas.add("tigger");
        maisUsadas.add("pokemon");
        maisUsadas.add("chelsea");
        maisUsadas.add("arsenal");
        maisUsadas.add("manutd");
        maisUsadas.add("everton");
        maisUsadas.add("jordan23");
        maisUsadas.add("santos");
        maisUsadas.add("esporte");
        maisUsadas.add("sport");
        maisUsadas.add("guest");
        maisUsadas.add("user");
        maisUsadas.add("mel ");
        maisUsadas.add("nina ");
        maisUsadas.add("billy ");
        maisUsadas.add("bob ");
        maisUsadas.add("susi ");
        maisUsadas.add("princesa ");
        maisUsadas.add("rex");
        maisUsadas.add("mimi ");
        maisUsadas.add("kito ");
        maisUsadas.add("nino ");
        maisUsadas.add("belinha ");
        maisUsadas.add("chiquinha ");
        maisUsadas.add("fredy");
        maisUsadas.add("thor");
        maisUsadas.add("bob");
        maisUsadas.add("fred");
        maisUsadas.add("billy");
        maisUsadas.add("nick");
        maisUsadas.add("chico");
        maisUsadas.add("jack");
        maisUsadas.add("marley");
        maisUsadas.add("bruce");
        maisUsadas.add("lucky");
        maisUsadas.add("luke");
        maisUsadas.add("max");
        maisUsadas.add("zeus");
        maisUsadas.add("ozzy");
        maisUsadas.add("theo");
        maisUsadas.add("pingo");
        maisUsadas.add("mike");
        maisUsadas.add("toddy");
        maisUsadas.add("zeca");
        maisUsadas.add("boris");
        maisUsadas.add("frederico");
        maisUsadas.add("simba");
        maisUsadas.add("buddy");
        maisUsadas.add("bud");
        maisUsadas.add("bidu");
        maisUsadas.add("tobias");
        maisUsadas.add("scooby");
        maisUsadas.add("mel");
        maisUsadas.add("nina");
        maisUsadas.add("luna");
        maisUsadas.add("lola");
        maisUsadas.add("lolla");
        maisUsadas.add("meg");
        maisUsadas.add("maggie");
        maisUsadas.add("amora");
        maisUsadas.add("belinha");
        maisUsadas.add("cacau");
        maisUsadas.add("bella/bela");
        maisUsadas.add("frida");
        maisUsadas.add("maya");
        maisUsadas.add("pandora");
        maisUsadas.add("malu");
        maisUsadas.add("princesa");
        maisUsadas.add("lua");
        maisUsadas.add("lilica");
        maisUsadas.add("sofia");
        maisUsadas.add("sophia");
        maisUsadas.add("jade");
        maisUsadas.add("kiara");
        maisUsadas.add("lili");
        maisUsadas.add("chanel");
        maisUsadas.add("fiona");
        maisUsadas.add("amy");
        maisUsadas.add("cindy");
        maisUsadas.add("dante");

        if (maisUsadas.contains(senha.toLowerCase())) {
            return "Sua senha esta na lista de senhas mais usadas no mundo ate o ano de 2018;";
        }

        return "";

    }
}
